apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "servicebus-cli.fullname" .}}
  namespace: {{ .Values.namespace.name }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: servicebus-cli