apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: servicebuscli
  namespace: {{ .Values.namespace }}
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: servicebuscli-deployment  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75