
{{- if .Values.app.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "servicebus-cli.serviceAccountName" . }}
  labels:
    {{- include "servicebus-cli.labels" . | nindent 4 }}
  {{- with .Values.app.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}