apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ include "servicebus-cli.fullname" .}}
  labels: 
    {{- include "servicebus-cli.labels" . | nindent 4 }}
spec: 
  {{- if .Values.app.scaling.enabled }}
  replicas: {{ .Values.app.scaling.startingReplicas }}
  {{- end }}
  selector: 
    matchLabels:
    {{- include "servicebus-cli.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: 
        {{- include "servicebus-cli.labels" . | nindent 8 }}
    spec:
      containers: 
      - name: servicebus-cli 
        image: cjlapao/servicebuscli:latest
        imagePullPolicy: {{ .Values.app.imagePullPolicy | quote }}
        ports:
        - containerPort: {{ .Values.app.port }}
        env:
          - name: SERVICEBUS_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: {{ include "servicebus-cli.fullname" .}}
                key: connectionString

          - name: SERVICEBUS_CLI_HTTP_PORT
            value: {{ .Values.app.port | quote }}
        resources:
          requests:
            cpu: {{ .Values.app.resources.requests.cpu | quote }}
            memory: {{ .Values.app.resources.requests.memory | quote }}
          limits:
            cpu: {{ .Values.app.resources.limits.cpu | quote }}
            memory: {{ .Values.app.resources.limits.memory | quote }}
