{{- if .Values.app.scaling.enabled }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "servicebus-cli.fullname" .}}
  namespace: {{ .Values.namespace.name }}
spec:
  minReplicas: {{ .Values.app.scaling.minReplicas }}
  maxReplicas: {{ .Values.app.scaling.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: servicebus-cli
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
{{- end }}