kind: Secret
apiVersion: v1
metadata:
  name: {{ include "servicebus-cli.fullname" .}}
  namespace: {{ .Values.namespace.name }}
stringData:
  connectionString: {{ .Values.secrets.serviceBusConnectionString }}
type: Opaque